/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatifRouteImport } from './routes/whatif'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClarifyRouteImport } from './routes/clarify'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'

const WhatifRoute = WhatifRouteImport.update({
  id: '/whatif',
  path: '/whatif',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarifyRoute = ClarifyRouteImport.update({
  id: '/clarify',
  path: '/clarify',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/category': typeof CategoryRoute
  '/clarify': typeof ClarifyRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
  '/progress': typeof ProgressRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/category': typeof CategoryRoute
  '/clarify': typeof ClarifyRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
  '/progress': typeof ProgressRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/category': typeof CategoryRoute
  '/clarify': typeof ClarifyRoute
  '/dashboard': typeof DashboardRoute
  '/details': typeof DetailsRoute
  '/progress': typeof ProgressRoute
  '/whatif': typeof WhatifRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/category'
    | '/clarify'
    | '/dashboard'
    | '/details'
    | '/progress'
    | '/whatif'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/category'
    | '/clarify'
    | '/dashboard'
    | '/details'
    | '/progress'
    | '/whatif'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/category'
    | '/clarify'
    | '/dashboard'
    | '/details'
    | '/progress'
    | '/whatif'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CategoryRoute: typeof CategoryRoute
  ClarifyRoute: typeof ClarifyRoute
  DashboardRoute: typeof DashboardRoute
  DetailsRoute: typeof DetailsRoute
  ProgressRoute: typeof ProgressRoute
  WhatifRoute: typeof WhatifRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatif': {
      id: '/whatif'
      path: '/whatif'
      fullPath: '/whatif'
      preLoaderRoute: typeof WhatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarify': {
      id: '/clarify'
      path: '/clarify'
      fullPath: '/clarify'
      preLoaderRoute: typeof ClarifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CategoryRoute: CategoryRoute,
  ClarifyRoute: ClarifyRoute,
  DashboardRoute: DashboardRoute,
  DetailsRoute: DetailsRoute,
  ProgressRoute: ProgressRoute,
  WhatifRoute: WhatifRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
